# Generated by Django 2.2.5 on 2019-11-11 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.Location', verbose_name='Ubicación'),
        ),
        migrations.AlterField(
            model_name='area',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.Location', verbose_name='Ubicación'),
        ),
    ]
