# Generated by Django 2.2.5 on 2019-11-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20191111_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='canton',
            field=models.CharField(max_length=50, verbose_name='Cantón'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_code',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parroquia',
            field=models.CharField(max_length=50, verbose_name='Parroquia'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(max_length=50, verbose_name='Provincia'),
        ),
    ]
