# Generated by Django 2.2.5 on 2019-11-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20191112_0621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='informe_code',
            field=models.CharField(max_length=20, verbose_name='Informe Código'),
        ),
    ]
