# Generated by Django 2.2.5 on 2019-11-13 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20191112_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informe',
            name='informe_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='informe',
            name='satimage1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informe1', to='reports.SatImage'),
        ),
        migrations.AlterField(
            model_name='informe',
            name='satimage2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informe2', to='reports.SatImage'),
        ),
        migrations.AlterField(
            model_name='location',
            name='canton',
            field=models.CharField(max_length=50, null=True, verbose_name='Cantón'),
        ),
        migrations.AlterField(
            model_name='location',
            name='parroquia',
            field=models.CharField(max_length=50, null=True, verbose_name='Parroquia'),
        ),
        migrations.AlterField(
            model_name='location',
            name='province',
            field=models.CharField(max_length=50, null=True, verbose_name='Provincia'),
        ),
    ]
